<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
    <AppxGeneratePrisForPortableLibrariesEnabled>false</AppxGeneratePrisForPortableLibrariesEnabled>
    <UseSdkBuildToolsPackage>true</UseSdkBuildToolsPackage>
    <SDKIdentifier></SDKIdentifier>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentCleaner\FluentCleaner.csproj" />
  </ItemGroup>

  <!-- Override MSBuild targets in Microsoft.Windows.SDK.BuildTools.MSIX targets to no-op for tests -->
  <Target Name="_GetSdkToolsPathsFromSdk" />
  <Target Name="_GetSdkToolsPathsFromPackage" />
  <Target Name="_GetSdkToolPaths" />
  <Target Name="_GetSdkToolPathsFromPackage" />
  <Target Name="_GetSdkToolPathsFromSdk" />

</Project>
